name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check-duplicate:
    name: Check duplicate action
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - name: Check duplicate
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'

  validate:
    name: Scala ${{ matrix.scala }}, Java ${{ matrix.java }}
    runs-on: ubuntu-20.04
    needs: check-duplicate
    if: >-
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip jvm]')

    env:
      SCALA_VERSION: ${{ matrix.scala }}

    strategy:
      fail-fast: false
      matrix:
        java: [adopt@1.8, adopt@1.11, adopt@1.15]
        scala: [2.12.13, 2.13.5, 3.0.0-M3]
        experimental: [false]

        include:
          - java: adopt@1.11
            scala: 0.27.0-RC1
            experimental: true

    steps:
      - name: Checkout repository
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/checkout@v2.3.4

      - name: Setup Scala
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Coursier
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Cache SBT
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION compile

      - name: Test
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION test

      - name: Scaladoc
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION doc

  # This is largely temporary, we'll find a better way to do this...
  validate-js:
    name: Scala-JS ${{ matrix.scala }}, Node ${{ matrix.node }}
    runs-on: ubuntu-20.04
    needs: check-duplicate
    if: >-
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip js]')

    env:
      SCALA_VERSION: ${{ matrix.scala }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 15]
        scala: [2.12.13, 2.13.5]

    steps:
      - name: Checkout repository
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Scala
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Cache SBT
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyJS/compile

      - name: Test
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyJS/test

      - name: Scaladoc
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyJS/doc

  validate-native:
    name: Scala-Native ${{ matrix.scala }} LLVM 10
    runs-on: ubuntu-20.04
    needs: check-duplicate
    if: >-
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip native]')

    env:
      SCALA_VERSION: ${{ matrix.scala }}

    strategy:
      fail-fast: false
      matrix:
        scala: [2.12.13, 2.13.5]

    steps:
      - name: Checkout repository
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/checkout@v2.3.4

      - name: Cache LLVM and Clang
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-10.0

      - name: Setup LLVM + Clang
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: KyleMayes/install-llvm-action@v1.1.1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Setup Scala
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Cache SBT
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyNative/compile

      - name: Test
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyNative/test

      - name: Scaladoc
        #if: needs.check-duplicate.outputs.should_skip != 'true'
        run: sbt ++$SCALA_VERSION parsleyNative/doc
  # End attrocity

  coverage:
    name: Test Coverage
    runs-on: ubuntu-20.04
    needs: validate
    if: >-
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip jvm]') &&
      (github.ref == 'refs/heads/master' && (needs.validate.result == 'success' || needs.validate.result == 'skipped') ||
       github.event_name == 'pull_request' && (needs.validate.result == 'success' || needs.validate.result == 'skipped'))

    env:
      SCALA_VERSION: 2.13.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11

      - name: Restore cached Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache

      - name: Restore cached SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Test with coverage
        run: sbt ++$SCALA_VERSION clean coverage test

      - name: Coverage report
        run: sbt ++$SCALA_VERSION coverageReport

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: d2376ef4077556821a44dd82803411deea8fd904d5008713754dda5f3ab42875
        with:
          coverageLocations: ${{github.workspace}}/jvm/target/scala-2.13/coverage-report/cobertura.xml:cobertura
